/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: chwrzvw5hacDdCDtmYaSSb
// Component: IV3Lp_147vp7

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import PageLayout from "../../components/PageLayout"; // plasmic-import: TZVmFGETAb0O/component
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../defaultStyles.css"; // plasmic-import: global/defaultcss
import "../antd_5_hostless/plasmic.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import "../plasmic_rich_components/plasmic.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import "../../components/plasmic/plasmic_my_project.css"; // plasmic-import: chwrzvw5hacDdCDtmYaSSb/projectcss
import "./PlasmicProfile.css"; // plasmic-import: IV3Lp_147vp7/css

createPlasmicElementProxy;

export type PlasmicProfile__VariantMembers = {};
export type PlasmicProfile__VariantsArgs = {};
type VariantPropType = keyof PlasmicProfile__VariantsArgs;
export const PlasmicProfile__VariantProps = new Array<VariantPropType>();

export type PlasmicProfile__ArgsType = {};
type ArgPropType = keyof PlasmicProfile__ArgsType;
export const PlasmicProfile__ArgProps = new Array<ArgPropType>();

export type PlasmicProfile__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  inputPhone?: Flex__<typeof AntdInput>;
  inputName?: Flex__<typeof AntdInput>;
  inputEmail?: Flex__<typeof AntdInput>;
  inputVerified?: Flex__<typeof AntdInput>;
  saveButton?: Flex__<typeof AntdButton>;
  save?: Flex__<"div">;
  queryButton?: Flex__<typeof AntdButton>;
};

export interface DefaultProfileProps {
  className?: string;
}

const $$ = {};

function PlasmicProfile__RenderFunc(props: {
  variants: PlasmicProfile__VariantsArgs;
  args: PlasmicProfile__ArgsType;
  overrides: PlasmicProfile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "inputPhone.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "inputName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "inputEmail.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "inputVerified.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "root_reset_chwrzvw5hacDdCDtmYaSSb",
            "plasmic_default_styles",
            "plasmic_mixins",
            "plasmic_tokens",
            "Profile__root__h7P0A"
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
          />

          <div
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Profile__freeBox__uJx6W"
            )}
          >
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__hmvVl"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__div",
                  "__wab_text",
                  "Profile__text__vYow4"
                )}
              >
                {"Telephone Number:"}
              </div>
            </div>
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__mhdoc"
              )}
            >
              {(() => {
                const child$Props = {
                  className: classNames(
                    "__wab_instance",
                    "Profile__inputPhone__zufGw"
                  ),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["inputPhone", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["inputPhone", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "inputPhone.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"inputPhone"}
                    data-plasmic-override={overrides.inputPhone}
                    {...child$Props}
                  />
                );
              })()}
            </div>
          </div>
          <div
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Profile__freeBox___0HkO"
            )}
          >
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__kbcUv"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__div",
                  "__wab_text",
                  "Profile__text__oG9It"
                )}
              >
                {"Name:"}
              </div>
            </div>
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__f8U"
              )}
            >
              {(() => {
                const child$Props = {
                  className: classNames(
                    "__wab_instance",
                    "Profile__inputName__vd1Xn"
                  ),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["inputName", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["inputName", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "inputName.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"inputName"}
                    data-plasmic-override={overrides.inputName}
                    {...child$Props}
                  />
                );
              })()}
            </div>
          </div>
          <div
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Profile__freeBox__q3RJ3"
            )}
          >
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__sDpuE"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__div",
                  "__wab_text",
                  "Profile__text__rtPpq"
                )}
              >
                {"Email Address:"}
              </div>
            </div>
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__fpCd"
              )}
            >
              {(() => {
                const child$Props = {
                  className: classNames(
                    "__wab_instance",
                    "Profile__inputEmail__nQiXd"
                  ),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["inputEmail", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["inputEmail", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "inputEmail.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"inputEmail"}
                    data-plasmic-override={overrides.inputEmail}
                    {...child$Props}
                  />
                );
              })()}
            </div>
          </div>
          <div
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Profile__freeBox___11K8"
            )}
          >
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__finz"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__div",
                  "__wab_text",
                  "Profile__text__myrDr"
                )}
              >
                {"Is Email Verified?"}
              </div>
            </div>
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox___9WiD"
              )}
            >
              {(() => {
                const child$Props = {
                  className: classNames(
                    "__wab_instance",
                    "Profile__inputVerified__lHwQg"
                  ),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["inputVerified", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, [
                    "inputVerified",
                    "value"
                  ])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "inputVerified.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"inputVerified"}
                    data-plasmic-override={overrides.inputVerified}
                    {...child$Props}
                  />
                );
              })()}
            </div>
          </div>
          <div
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Profile__freeBox__e5AnC"
            )}
          >
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox__jw0Dw"
              )}
            />

            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Profile__freeBox___3QYhw"
              )}
            >
              <AntdButton
                data-plasmic-name={"saveButton"}
                data-plasmic-override={overrides.saveButton}
                className={classNames(
                  "__wab_instance",
                  "Profile__saveButton___7Mui9"
                )}
              >
                <div
                  data-plasmic-name={"save"}
                  data-plasmic-override={overrides.save}
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__div",
                    "__wab_text",
                    "Profile__save__xkV5A"
                  )}
                >
                  {"Save"}
                </div>
              </AntdButton>
              <AntdButton
                data-plasmic-name={"queryButton"}
                data-plasmic-override={overrides.queryButton}
                className={classNames(
                  "__wab_instance",
                  "Profile__queryButton___0CcoL"
                )}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__div",
                    "__wab_text",
                    "Profile__text__wewLh"
                  )}
                >
                  {"Query"}
                </div>
              </AntdButton>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "inputPhone",
    "inputName",
    "inputEmail",
    "inputVerified",
    "saveButton",
    "save",
    "queryButton"
  ],
  pageLayout: ["pageLayout"],
  inputPhone: ["inputPhone"],
  inputName: ["inputName"],
  inputEmail: ["inputEmail"],
  inputVerified: ["inputVerified"],
  saveButton: ["saveButton", "save"],
  save: ["save"],
  queryButton: ["queryButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  inputPhone: typeof AntdInput;
  inputName: typeof AntdInput;
  inputEmail: typeof AntdInput;
  inputVerified: typeof AntdInput;
  saveButton: typeof AntdButton;
  save: "div";
  queryButton: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProfile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProfile__VariantsArgs;
    args?: PlasmicProfile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProfile__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProfile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProfile__ArgProps,
          internalVariantPropNames: PlasmicProfile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfile";
  } else {
    func.displayName = `PlasmicProfile.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "chwrzvw5hacDdCDtmYaSSb"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicProfile = Object.assign(
  // Top-level PlasmicProfile renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    inputPhone: makeNodeComponent("inputPhone"),
    inputName: makeNodeComponent("inputName"),
    inputEmail: makeNodeComponent("inputEmail"),
    inputVerified: makeNodeComponent("inputVerified"),
    saveButton: makeNodeComponent("saveButton"),
    save: makeNodeComponent("save"),
    queryButton: makeNodeComponent("queryButton"),

    // Metadata about props expected for PlasmicProfile
    internalVariantProps: PlasmicProfile__VariantProps,
    internalArgProps: PlasmicProfile__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProfile;
/* prettier-ignore-end */
