/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kPtL4UpULb2Exm5C4cyhzL
// Component: BYOvFrXHBGpA

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseButton } from "@plasmicpkgs/react-aria/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../defaultStyles.css"; // plasmic-import: global/defaultcss
import "../antd_5_hostless/plasmic.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import "../plasmic_rich_components/plasmic.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import "../library_tailwind_3_4_color_tokens/plasmic.css"; // plasmic-import: 5ZtnypMovRHeeP3YTdPCYL/projectcss
import "../library_tailwind_3_4_number_tokens/plasmic.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import "../../components/plasmic/plasmic_my_project.css"; // plasmic-import: kPtL4UpULb2Exm5C4cyhzL/projectcss
import "./PlasmicButton.css"; // plasmic-import: BYOvFrXHBGpA/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: b0QDi7GnhEEB/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: a5i7ADyOn1ty/icon

createPlasmicElementProxy;

export type PlasmicButton__VariantMembers = {
  color: "neutral" | "muted" | "success" | "warning" | "errorDestructive";
  type: "soft" | "bordered";
  size: "extraSmall" | "small" | "large" | "extraLarge";
  iconStart: "iconStart";
  iconEnd: "iconEnd";
  roundedFull: "roundedFull";
  flatSide: "top" | "right" | "bottom" | "left";
};
export type PlasmicButton__VariantsArgs = {
  color?: SingleChoiceArg<
    "neutral" | "muted" | "success" | "warning" | "errorDestructive"
  >;
  type?: SingleChoiceArg<"soft" | "bordered">;
  size?: SingleChoiceArg<"extraSmall" | "small" | "large" | "extraLarge">;
  iconStart?: SingleBooleanChoiceArg<"iconStart">;
  iconEnd?: SingleBooleanChoiceArg<"iconEnd">;
  roundedFull?: SingleBooleanChoiceArg<"roundedFull">;
  flatSide?: MultiChoiceArg<"top" | "right" | "bottom" | "left">;
};
type VariantPropType = keyof PlasmicButton__VariantsArgs;
export const PlasmicButton__VariantProps = new Array<VariantPropType>(
  "color",
  "type",
  "size",
  "iconStart",
  "iconEnd",
  "roundedFull",
  "flatSide"
);

export type PlasmicButton__ArgsType = {
  disabled?: boolean;
  submitsForm?: boolean;
  resetsForm?: boolean;
  ariaLabel?: string;
  onClick?: (event: any) => void;
  linkTo?: string;
  openLinkInNewTab?: boolean;
  start?: React.ReactNode;
  label?: React.ReactNode;
  end?: React.ReactNode;
};
type ArgPropType = keyof PlasmicButton__ArgsType;
export const PlasmicButton__ArgProps = new Array<ArgPropType>(
  "disabled",
  "submitsForm",
  "resetsForm",
  "ariaLabel",
  "onClick",
  "linkTo",
  "openLinkInNewTab",
  "start",
  "label",
  "end"
);

export type PlasmicButton__OverridesType = {
  root?: Flex__<typeof BaseButton>;
  softBackground?: Flex__<"div">;
  border?: Flex__<"div">;
  interactionEffect?: Flex__<"div">;
};

export interface DefaultButtonProps {
  disabled?: boolean;
  submitsForm?: boolean;
  resetsForm?: boolean;
  ariaLabel?: string;
  onClick?: (event: any) => void;
  linkTo?: string;
  openLinkInNewTab?: boolean;
  start?: React.ReactNode;
  label?: React.ReactNode;
  end?: React.ReactNode;
  color?: SingleChoiceArg<
    "neutral" | "muted" | "success" | "warning" | "errorDestructive"
  >;
  type?: SingleChoiceArg<"soft" | "bordered">;
  size?: SingleChoiceArg<"extraSmall" | "small" | "large" | "extraLarge">;
  iconStart?: SingleBooleanChoiceArg<"iconStart">;
  iconEnd?: SingleBooleanChoiceArg<"iconEnd">;
  roundedFull?: SingleBooleanChoiceArg<"roundedFull">;
  flatSide?: MultiChoiceArg<"top" | "right" | "bottom" | "left">;
  className?: string;
}

const $$ = {};

function PlasmicButton__RenderFunc(props: {
  variants: PlasmicButton__VariantsArgs;
  args: PlasmicButton__ArgsType;
  overrides: PlasmicButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          linkTo: "",
          openLinkInNewTab: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.color
      },
      {
        path: "size",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.size
      },
      {
        path: "iconStart",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.iconStart
      },
      {
        path: "iconEnd",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.iconEnd
      },
      {
        path: "roundedFull",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.roundedFull
      },
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.type
      },
      {
        path: "flatSide",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.flatSide
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    disabled: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseButton
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      className={classNames(
        "__wab_instance",
        "root_reset_kPtL4UpULb2Exm5C4cyhzL",
        "plasmic_default_styles",
        "plasmic_mixins",
        "plasmic_tokens",
        "Button__root__yuzNk",
        {
          Button__rootcolor_errorDestructive__yuzNk7XkmV: hasVariant(
            $state,
            "color",
            "errorDestructive"
          ),
          Button__rootcolor_errorDestructive_type_bordered__yuzNk7XkmVL05CT:
            hasVariant($state, "color", "errorDestructive") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_errorDestructive_type_soft__yuzNk7XkmVVd26K:
            hasVariant($state, "color", "errorDestructive") &&
            hasVariant($state, "type", "soft"),
          Button__rootcolor_muted__yuzNkdpTG: hasVariant(
            $state,
            "color",
            "muted"
          ),
          Button__rootcolor_muted_type_bordered__yuzNkdpTGL05CT:
            hasVariant($state, "color", "muted") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_muted_type_soft__yuzNkdpTGVd26K:
            hasVariant($state, "color", "muted") &&
            hasVariant($state, "type", "soft"),
          Button__rootcolor_neutral__yuzNkfhbkK: hasVariant(
            $state,
            "color",
            "neutral"
          ),
          Button__rootcolor_neutral_type_bordered__yuzNkfhbkKL05CT:
            hasVariant($state, "color", "neutral") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_neutral_type_soft__yuzNkfhbkKVd26K:
            hasVariant($state, "color", "neutral") &&
            hasVariant($state, "type", "soft"),
          Button__rootcolor_success__yuzNkNuiG: hasVariant(
            $state,
            "color",
            "success"
          ),
          Button__rootcolor_success_type_bordered__yuzNkNuiGL05CT:
            hasVariant($state, "color", "success") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_success_type_soft__yuzNkNuiGVd26K:
            hasVariant($state, "color", "success") &&
            hasVariant($state, "type", "soft"),
          Button__rootcolor_warning__yuzNkwgWgG: hasVariant(
            $state,
            "color",
            "warning"
          ),
          Button__rootflatSide_bottom__yuzNkj5MwT: hasVariant(
            $state,
            "flatSide",
            "bottom"
          ),
          Button__rootflatSide_left__yuzNk8B7Zu: hasVariant(
            $state,
            "flatSide",
            "left"
          ),
          Button__rootflatSide_right__yuzNkMkGUm: hasVariant(
            $state,
            "flatSide",
            "right"
          ),
          Button__rootflatSide_top__yuzNka8PG: hasVariant(
            $state,
            "flatSide",
            "top"
          ),
          Button__rooticonEnd__yuzNk6Y3Cw: hasVariant(
            $state,
            "iconEnd",
            "iconEnd"
          ),
          Button__rooticonStart__yuzNkQk1Q: hasVariant(
            $state,
            "iconStart",
            "iconStart"
          ),
          Button__rootroundedFull__yuzNkLjepv: hasVariant(
            $state,
            "roundedFull",
            "roundedFull"
          ),
          Button__rootsize_extraLarge__yuzNkr2Mbd: hasVariant(
            $state,
            "size",
            "extraLarge"
          ),
          Button__rootsize_extraSmall__yuzNkEm7OB: hasVariant(
            $state,
            "size",
            "extraSmall"
          ),
          Button__rootsize_large__yuzNkBBaa: hasVariant(
            $state,
            "size",
            "large"
          ),
          Button__rootsize_small__yuzNkYGcIy: hasVariant(
            $state,
            "size",
            "small"
          ),
          Button__roottype_bordered__yuzNkl05CT: hasVariant(
            $state,
            "type",
            "bordered"
          ),
          Button__roottype_bordered_color_warning__yuzNkl05CTWgWgG:
            hasVariant($state, "color", "warning") &&
            hasVariant($state, "type", "bordered"),
          Button__roottype_soft__yuzNkvd26K: hasVariant($state, "type", "soft"),
          Button__roottype_soft_color_warning__yuzNkvd26KWgWgG:
            hasVariant($state, "color", "warning") &&
            hasVariant($state, "type", "soft")
        }
      )}
      href={args.linkTo}
      isDisabled={args.disabled}
      onPress={args.onClick}
      plasmicUpdateVariant={updateVariant}
      resetsForm={args.resetsForm}
      submitsForm={args.submitsForm}
      target={(() => {
        try {
          return $props.openLinkInNewTab ? "_blank" : "_self";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}
    >
      {(
        hasVariant($state, "type", "bordered") && $ccVariants["pressed"]
          ? true
          : hasVariant($state, "type", "bordered") && $ccVariants["hovered"]
          ? true
          : hasVariant($state, "type", "soft")
          ? true
          : false
      ) ? (
        <div
          data-plasmic-name={"softBackground"}
          data-plasmic-override={overrides.softBackground}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "Button__softBackground___9OgK",
            {
              Button__softBackgroundcolor_errorDestructive___9OgK7XkmV:
                hasVariant($state, "color", "errorDestructive"),
              Button__softBackgroundcolor_muted___9OgKdpTG: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__softBackgroundcolor_neutral___9OgKfhbkK: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__softBackgroundcolor_success___9OgKNuiG: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__softBackgroundcolor_warning___9OgKwgWgG: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__softBackgroundroundedFull___9OgKLjepv: hasVariant(
                $state,
                "roundedFull",
                "roundedFull"
              ),
              Button__softBackgroundsize_large___9OgKBBaa: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__softBackgroundtype_bordered___9OgKl05CT: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__softBackgroundtype_soft___9OgKvd26K: hasVariant(
                $state,
                "type",
                "soft"
              )
            }
          )}
        />
      ) : null}
      {(hasVariant($state, "type", "bordered") ? true : false) ? (
        <div
          data-plasmic-name={"border"}
          data-plasmic-override={overrides.border}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "Button__border__tj0UG",
            {
              Button__bordercolor_errorDestructive__tj0UG7XkmV: hasVariant(
                $state,
                "color",
                "errorDestructive"
              ),
              Button__bordercolor_muted__tj0UGdpTG: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__bordercolor_muted_type_bordered__tj0UGdpTGL05CT:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "bordered"),
              Button__bordercolor_neutral__tj0UGfhbkK: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__bordercolor_success__tj0UGnuiG: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__bordercolor_warning__tj0UGwgWgG: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__borderflatSide_bottom__tj0UGj5MwT: hasVariant(
                $state,
                "flatSide",
                "bottom"
              ),
              Button__borderflatSide_left__tj0UG8B7Zu: hasVariant(
                $state,
                "flatSide",
                "left"
              ),
              Button__borderflatSide_right__tj0UGMkGUm: hasVariant(
                $state,
                "flatSide",
                "right"
              ),
              Button__borderflatSide_top__tj0UGa8PG: hasVariant(
                $state,
                "flatSide",
                "top"
              ),
              Button__borderroundedFull__tj0UGljepv: hasVariant(
                $state,
                "roundedFull",
                "roundedFull"
              ),
              Button__bordersize_large__tj0UGbBaa: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__bordertype_bordered__tj0UGl05CT: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__bordertype_soft__tj0UGvd26K: hasVariant(
                $state,
                "type",
                "soft"
              )
            }
          )}
        />
      ) : null}
      <div
        data-plasmic-name={"interactionEffect"}
        data-plasmic-override={overrides.interactionEffect}
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "Button__interactionEffect__edm3",
          {
            Button__interactionEffectcolor_errorDestructive__edm37XkmV:
              hasVariant($state, "color", "errorDestructive"),
            Button__interactionEffectcolor_muted__edm3DpTG: hasVariant(
              $state,
              "color",
              "muted"
            ),
            Button__interactionEffectcolor_neutral__edm3FhbkK: hasVariant(
              $state,
              "color",
              "neutral"
            ),
            Button__interactionEffectcolor_success__edm3NuiG: hasVariant(
              $state,
              "color",
              "success"
            ),
            Button__interactionEffectcolor_success_type_bordered__edm3NuiGL05CT:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "bordered"),
            Button__interactionEffectcolor_warning__edm3WgWgG: hasVariant(
              $state,
              "color",
              "warning"
            ),
            Button__interactionEffectroundedFull__edm3Ljepv: hasVariant(
              $state,
              "roundedFull",
              "roundedFull"
            ),
            Button__interactionEffectsize_large__edm3BBaa: hasVariant(
              $state,
              "size",
              "large"
            ),
            Button__interactionEffectsize_small__edm3YGcIy: hasVariant(
              $state,
              "size",
              "small"
            ),
            Button__interactionEffecttype_bordered__edm3L05CT: hasVariant(
              $state,
              "type",
              "bordered"
            ),
            Button__interactionEffecttype_soft__edm3Vd26K: hasVariant(
              $state,
              "type",
              "soft"
            )
          }
        )}
        style={
          hasVariant($state, "type", "bordered") && $ccVariants["pressed"]
            ? { display: "block" }
            : undefined
        }
      />

      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "Button__freeBox__t2BTr",
          {
            Button__freeBoxcolor_neutral__t2BTrfhbkK: hasVariant(
              $state,
              "color",
              "neutral"
            ),
            Button__freeBoxcolor_success_type_bordered__t2BTrNuiGL05CT:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "bordered"),
            Button__freeBoxroundedFull__t2BTrLjepv: hasVariant(
              $state,
              "roundedFull",
              "roundedFull"
            ),
            Button__freeBoxsize_extraLarge__t2BTrr2Mbd: hasVariant(
              $state,
              "size",
              "extraLarge"
            ),
            Button__freeBoxsize_extraSmall__t2BTrEm7OB: hasVariant(
              $state,
              "size",
              "extraSmall"
            ),
            Button__freeBoxsize_large__t2BTrBBaa: hasVariant(
              $state,
              "size",
              "large"
            ),
            Button__freeBoxsize_small__t2BTrYGcIy: hasVariant(
              $state,
              "size",
              "small"
            ),
            Button__freeBoxtype_bordered__t2BTrl05CT: hasVariant(
              $state,
              "type",
              "bordered"
            )
          }
        )}
      >
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "Button__freeBox__bcftm",
            {
              Button__freeBoxcolor_neutral__bcftmfhbkK: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__freeBoxcolor_neutral_type_soft__bcftmfhbkKVd26K:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "soft"),
              Button__freeBoxiconStart__bcftmQk1Q: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              ),
              Button__freeBoxsize_extraLarge__bcftmr2Mbd: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__freeBoxsize_large__bcftmBBaa: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__freeBoxsize_small__bcftmYGcIy: hasVariant(
                $state,
                "size",
                "small"
              ),
              Button__freeBoxtype_bordered__bcftml05CT: hasVariant(
                $state,
                "type",
                "bordered"
              )
            }
          )}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <CircleIcon
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__svg",
                  "Button__svg__vIr13"
                )}
                role={"img"}
              />
            ),

            value: args.start,
            className: classNames("Button__slotTargetStart__cUeMi", {
              Button__slotTargetStartcolor_errorDestructive__cUeMi7XkmV:
                hasVariant($state, "color", "errorDestructive"),
              Button__slotTargetStartcolor_errorDestructive_type_bordered__cUeMi7XkmVL05CT:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_errorDestructive_type_soft__cUeMi7XkmVVd26K:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStartcolor_muted__cUeMidpTG: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__slotTargetStartcolor_muted_type_bordered__cUeMidpTGL05CT:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_muted_type_soft__cUeMidpTGVd26K:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStartcolor_neutral__cUeMifhbkK: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__slotTargetStartcolor_neutral_type_bordered__cUeMifhbkKL05CT:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_neutral_type_soft__cUeMifhbkKVd26K:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStartcolor_success__cUeMiNuiG: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__slotTargetStartcolor_success_type_bordered__cUeMiNuiGL05CT:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_success_type_soft__cUeMiNuiGVd26K:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStartcolor_warning__cUeMiwgWgG: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__slotTargetStarticonStart__cUeMiQk1Q: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              ),
              Button__slotTargetStartsize_extraLarge__cUeMir2Mbd: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__slotTargetStartsize_extraSmall__cUeMiEm7OB: hasVariant(
                $state,
                "size",
                "extraSmall"
              ),
              Button__slotTargetStartsize_large__cUeMiBBaa: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__slotTargetStartsize_small__cUeMiYGcIy: hasVariant(
                $state,
                "size",
                "small"
              ),
              Button__slotTargetStarttype_bordered__cUeMil05CT: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__slotTargetStarttype_bordered_color_warning__cUeMil05CTWgWgG:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStarttype_soft__cUeMivd26K: hasVariant(
                $state,
                "type",
                "soft"
              ),
              Button__slotTargetStarttype_soft_color_warning__cUeMivd26KWgWgG:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "soft")
            })
          })}
        </div>
        {renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "Button__text___7EuEg"
              )}
            >
              {"Text"}
            </div>
          ),
          value: args.label,
          className: classNames("Button__slotTargetLabel__mrm4W", {
            Button__slotTargetLabelcolor_errorDestructive__mrm4W7XkmV:
              hasVariant($state, "color", "errorDestructive"),
            Button__slotTargetLabelcolor_errorDestructive_type_bordered__mrm4W7XkmVL05CT:
              hasVariant($state, "color", "errorDestructive") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_errorDestructive_type_soft__mrm4W7XkmVVd26K:
              hasVariant($state, "color", "errorDestructive") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabelcolor_muted__mrm4WdpTG: hasVariant(
              $state,
              "color",
              "muted"
            ),
            Button__slotTargetLabelcolor_muted_type_bordered__mrm4WdpTGL05CT:
              hasVariant($state, "color", "muted") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_muted_type_soft__mrm4WdpTGVd26K:
              hasVariant($state, "color", "muted") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabelcolor_neutral__mrm4WfhbkK: hasVariant(
              $state,
              "color",
              "neutral"
            ),
            Button__slotTargetLabelcolor_neutral_type_bordered__mrm4WfhbkKL05CT:
              hasVariant($state, "color", "neutral") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_neutral_type_soft__mrm4WfhbkKVd26K:
              hasVariant($state, "color", "neutral") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabelcolor_success__mrm4WnuiG: hasVariant(
              $state,
              "color",
              "success"
            ),
            Button__slotTargetLabelcolor_success_type_bordered__mrm4WnuiGL05CT:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_success_type_soft__mrm4WnuiGVd26K:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabelcolor_warning__mrm4WwgWgG: hasVariant(
              $state,
              "color",
              "warning"
            ),
            Button__slotTargetLabeliconEnd__mrm4W6Y3Cw: hasVariant(
              $state,
              "iconEnd",
              "iconEnd"
            ),
            Button__slotTargetLabeliconStart__mrm4Wqk1Q: hasVariant(
              $state,
              "iconStart",
              "iconStart"
            ),
            Button__slotTargetLabelsize_extraLarge__mrm4Wr2Mbd: hasVariant(
              $state,
              "size",
              "extraLarge"
            ),
            Button__slotTargetLabelsize_extraSmall__mrm4Wem7OB: hasVariant(
              $state,
              "size",
              "extraSmall"
            ),
            Button__slotTargetLabelsize_large__mrm4WbBaa: hasVariant(
              $state,
              "size",
              "large"
            ),
            Button__slotTargetLabelsize_small__mrm4WyGcIy: hasVariant(
              $state,
              "size",
              "small"
            ),
            Button__slotTargetLabeltype_bordered__mrm4Wl05CT: hasVariant(
              $state,
              "type",
              "bordered"
            ),
            Button__slotTargetLabeltype_bordered_color_warning__mrm4Wl05CTWgWgG:
              hasVariant($state, "color", "warning") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabeltype_soft__mrm4Wvd26K: hasVariant(
              $state,
              "type",
              "soft"
            ),
            Button__slotTargetLabeltype_soft_color_warning__mrm4Wvd26KWgWgG:
              hasVariant($state, "color", "warning") &&
              hasVariant($state, "type", "soft")
          })
        })}
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "Button__freeBox__lQuG",
            {
              Button__freeBoxiconEnd__lQuG6Y3Cw: hasVariant(
                $state,
                "iconEnd",
                "iconEnd"
              ),
              Button__freeBoxsize_extraLarge__lQuGR2Mbd: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__freeBoxsize_large__lQuGBBaa: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__freeBoxsize_small__lQuGYGcIy: hasVariant(
                $state,
                "size",
                "small"
              )
            }
          )}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <ChevronDownIcon
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__svg",
                  "Button__svg___1S2F7"
                )}
                role={"img"}
              />
            ),

            value: args.end,
            className: classNames("Button__slotTargetEnd__aNzge", {
              Button__slotTargetEndcolor_errorDestructive__aNzge7XkmV:
                hasVariant($state, "color", "errorDestructive"),
              Button__slotTargetEndcolor_errorDestructive_type_bordered__aNzge7XkmVL05CT:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_errorDestructive_type_soft__aNzge7XkmVVd26K:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndcolor_muted__aNzgedpTG: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__slotTargetEndcolor_muted_type_bordered__aNzgedpTGL05CT:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_muted_type_soft__aNzgedpTGVd26K:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndcolor_neutral__aNzgefhbkK: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__slotTargetEndcolor_neutral_type_bordered__aNzgefhbkKL05CT:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_neutral_type_soft__aNzgefhbkKVd26K:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndcolor_success__aNzgeNuiG: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__slotTargetEndcolor_success_type_bordered__aNzgeNuiGL05CT:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_success_type_soft__aNzgeNuiGVd26K:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndcolor_warning__aNzgewgWgG: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__slotTargetEndiconEnd__aNzge6Y3Cw: hasVariant(
                $state,
                "iconEnd",
                "iconEnd"
              ),
              Button__slotTargetEndiconStart__aNzgeQk1Q: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              ),
              Button__slotTargetEndsize_extraLarge__aNzger2Mbd: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__slotTargetEndsize_extraSmall__aNzgeEm7OB: hasVariant(
                $state,
                "size",
                "extraSmall"
              ),
              Button__slotTargetEndsize_large__aNzgeBBaa: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__slotTargetEndsize_small__aNzgeYGcIy: hasVariant(
                $state,
                "size",
                "small"
              ),
              Button__slotTargetEndtype_bordered__aNzgel05CT: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__slotTargetEndtype_bordered_color_warning__aNzgel05CTWgWgG:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndtype_soft__aNzgevd26K: hasVariant(
                $state,
                "type",
                "soft"
              ),
              Button__slotTargetEndtype_soft_color_warning__aNzgevd26KWgWgG:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "soft")
            })
          })}
        </div>
      </Stack__>
    </BaseButton>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "softBackground", "border", "interactionEffect"],
  softBackground: ["softBackground"],
  border: ["border"],
  interactionEffect: ["interactionEffect"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof BaseButton;
  softBackground: "div";
  border: "div";
  interactionEffect: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButton__VariantsArgs;
    args?: PlasmicButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButton__ArgProps,
          internalVariantPropNames: PlasmicButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton";
  } else {
    func.displayName = `PlasmicButton.${nodeName}`;
  }
  return func;
}

export const PlasmicButton = Object.assign(
  // Top-level PlasmicButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    softBackground: makeNodeComponent("softBackground"),
    border: makeNodeComponent("border"),
    interactionEffect: makeNodeComponent("interactionEffect"),

    // Metadata about props expected for PlasmicButton
    internalVariantProps: PlasmicButton__VariantProps,
    internalArgProps: PlasmicButton__ArgProps
  }
);

export default PlasmicButton;
/* prettier-ignore-end */
